//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Simple.Data.Informix.Tests.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Simple.Data.Informix.Tests.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B|billing error|
        ///D|damaged goods|
        ///I|incorrect merchandise sent|
        ///L|late shipment|
        ///O|other|
        ///.
        /// </summary>
        internal static string call_type {
            get {
                return ResourceManager.GetString("call_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10001|1|HRO|Brown leather. Specify first baseman&apos;s or infield/outfield style.  Specify right- or left-handed.||Your First Season&apos;s Baseball Glove|
        ///10002|1|HSK|Babe Ruth signature glove. Black leather. Infield/outfield style. Specify right- or left-handed.||All Leather, Hand Stitched, Deep Pockets, Sturdy Webbing That Won&apos;t Let Go|
        ///10003|1|SMT|Catcher&apos;s mitt. Brown leather. Specify right- or left-handed.||A Sturdy Catcher&apos;s Mitt With the Perfect Pocket|
        ///10004|2|HRO|Jackie Robinson signature ball. Highest  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string catalog {
            get {
                return ResourceManager.GetString("catalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 106|1994-06-12 8:20|maryj|D|Order was received, but two of the cans of ANZ tennis balls within the case were empty|1994-06-12 8:25|Authorized credit for two cans to customer, issued apology. Called ANZ buyer to report the QA problem.|
        ///110|1994-07-07 10:24|richc|L|Order placed one month ago (6/7) not received.|1994-07-07 10:30|Checked with shipping (Ed Smith). Order sent yesterday- we were waiting for goods from ANZ. Next time will call with delay if necessary.|
        ///119|1994-07-01 15:00|richc|B|Bill does not r [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string cust_calls {
            get {
                return ResourceManager.GetString("cust_calls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 101|Ludwig|Pauli|All Sports Supplies|213 Erstwild Court||Sunnyvale|CA|94086|408-789-8075|
        ///102|Carole|Sadler|Sports Spot|785 Geary St||San Francisco|CA|94117|415-822-1289|
        ///103|Philip|Currie|Phil&apos;s Sports|654 Poplar|P. O. Box 3498|Palo Alto|CA|94303|415-328-4543|
        ///104|Anthony|Higgins|Play Ball!|East Shopping Cntr.|422 Bay Road|Redwood City|CA|94026|415-368-1100|
        ///105|Raymond|Vector|Los Altos Sports|1899 La Loma Drive||Los Altos|CA|94022|415-776-3249|
        ///106|George|Watson|Watson &amp; Son|1143 Carver Place||Mounta [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string customer {
            get {
                return ResourceManager.GetString("customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1|1001|1|HRO|1|250.0|
        ///1|1002|4|HSK|1|960.0|
        ///2|1002|3|HSK|1|240.0|
        ///1|1003|9|ANZ|1|20.0|
        ///2|1003|8|ANZ|1|840.0|
        ///3|1003|5|ANZ|5|99.0|
        ///1|1004|1|HRO|1|250.0|
        ///2|1004|2|HRO|1|126.0|
        ///3|1004|3|HSK|1|240.0|
        ///4|1004|1|HSK|1|800.0|
        ///1|1005|5|NRG|10|280.0|
        ///2|1005|5|ANZ|10|198.0|
        ///3|1005|6|SMT|1|36.0|
        ///4|1005|6|ANZ|1|48.0|
        ///1|1006|5|SMT|5|125.0|
        ///2|1006|5|NRG|5|140.0|
        ///3|1006|5|ANZ|5|99.0|
        ///4|1006|6|SMT|1|36.0|
        ///5|1006|6|ANZ|1|48.0|
        ///1|1007|1|HRO|1|250.0|
        ///2|1007|2|HRO|1|126.0|
        ///3|1007|3|HSK|1|240.0|
        ///4|1007|4|HR [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string items {
            get {
                return ResourceManager.GetString("items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMT|Smith|3|
        ///ANZ|Anza|5|
        ///NRG|Norge|7|
        ///HSK|Husky|5|
        ///HRO|Hero|4|
        ///SHM|Shimara|30|
        ///KAR|Karsten|21|
        ///NKL|Nikolus|8|
        ///PRC|ProCycle|9|
        ///.
        /// </summary>
        internal static string manufact {
            get {
                return ResourceManager.GetString("manufact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1001|05/20/1994|104|express|n|B77836|06/01/1994|20.4|10.0|07/22/1994|
        ///1002|05/21/1994|101|PO on box; deliver to back door only|n|9270|05/26/1994|50.6|15.3|06/03/1994|
        ///1003|05/22/1994|104|express|n|B77890|05/23/1994|35.6|10.8|06/14/1994|
        ///1004|05/22/1994|106|ring bell twice|y|8006|05/30/1994|95.8|19.2||
        ///1005|05/24/1994|116|call before delivery|n|2865|06/09/1994|80.8|16.2|06/21/1994|
        ///1006|05/30/1994|112|after 10 am|y|Q13557||70.8|14.2||
        ///1007|05/31/1994|117||n|278693|06/05/1994|125.9|25.2||
        ///1008|06/07/19 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string orders {
            get {
                return ResourceManager.GetString("orders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AK|Alaska|
        ///HI|Hawaii|
        ///CA|California|
        ///OR|Oregon|
        ///WA|Washington|
        ///ID|Idaho|
        ///NV|Nevada|
        ///MT|Montana|
        ///WY|Wyoming|
        ///UT|Utah|
        ///AZ|Arizona|
        ///NM|New Mexico|
        ///CO|Colorado|
        ///ND|North Dakota|
        ///SD|South Dakota|
        ///NE|Nebraska|
        ///KS|Kansas|
        ///OK|Oklahoma|
        ///TX|Texas|
        ///MN|Minnesota|
        ///IA|Iowa|
        ///MO|Missouri|
        ///AR|Arkansas|
        ///LA|Louisiana|
        ///WI|Wisconsin|
        ///IL|Illinois|
        ///MS|Mississippi|
        ///AL|Alabama|
        ///FL|Florida|
        ///GA|Georgia|
        ///SC|South Carolina|
        ///NC|North Carolina|
        ///TN|Tennessee|
        ///KY|Kentucky|
        ///VA|Virginia|
        ///WV|West Virginia|
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string state {
            get {
                return ResourceManager.GetString("state", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1|HRO|baseball gloves|250.00|case|10 gloves/case|
        ///1|HSK|baseball gloves|800.00|case|10 gloves/case|
        ///1|SMT|baseball gloves|450.00|case|10 gloves/case|
        ///2|HRO|baseball|126.00|case|24/case|
        ///3|HSK|baseball bat|240.00|case|12/case|
        ///3|SHM|baseball bat|280.00|case|12/case|
        ///4|HSK|football|960.00|case|24/case|
        ///4|HRO|football|480.00|case|24/case|
        ///5|NRG|tennis racquet|28.00|each|each|
        ///5|SMT|tennis racquet|25.00|each|each|
        ///5|ANZ|tennis racquet|19.80|each|each|
        ///6|SMT|tennis ball|36.00|case|24 cans/case|
        ///6|ANZ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string stock {
            get {
                return ResourceManager.GetString("stock", resourceCulture);
            }
        }
    }
}
